from datetime import datetime
from time import time

import jwt
from flask import current_app
from werkzeug.security import generate_password_hash, check_password_hash

from server.app import db, jwt_manager
from server.utils.time import date_from_str


@jwt_manager.user_identity_loader
def user_identity_lookup(user):
    return user.id


@jwt_manager.user_lookup_loader
def user_lookup_callback(_jwt_header, jwt_data):
    return get_user_by_id(jwt_data.get("sub"))


def add(db_object):
    try:
        db.session.add(db_object)
        db.session.commit()
    except Exception as e:
        print(e)
        db.session.rollback()
        raise


def delete_obj(db_object):
    try:
        db.session.delete(db_object)
        db.session.commit()
    except Exception as e:
        print(e)
        db.session.rollback()
        raise


member_to_event = db.Table(
    'member_to_event',
    db.Column('event_id', db.Integer, db.ForeignKey('event.id')),
    db.Column('member_id', db.Integer, db.ForeignKey('event_member.id')),
)

product_to_event = db.Table(
    'product_to_event',
    db.Column('event_id', db.Integer, db.ForeignKey('event.id')),
    db.Column('product_id', db.Integer, db.ForeignKey('product.id')),
)


class User(db.Model):
    """User model

    :cvar id: autogenerated user id
    :type id: int
    :cvar username: unique username
    :type username: str
    :cvar full_name: full name
    :type full_name: str
    :cvar email: user email
    :type email: str
    :cvar phone: users phone number
    :type phone: str
    :cvar contacts: any other user contacts
    :type contacts: str
    :cvar is_email_verified: True after verifying email
    :type is_email_verified: bool
    :cvar pwd: hash of users password
    :type pwd: str
    :cvar timestamp: account creation date
    :type timestamp: datetime

    """

    def __init__(self, user_data: dict):
        self.username = user_data.get('username')
        self.full_name = user_data.get('full_name')
        self.email = user_data.get('email')
        self.phone = user_data.get('phone')
        self.contacts = user_data.get('contacts')
        self.pwd = generate_password_hash(user_data.get('pwd'))

    __tablename__ = 'user'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(50), unique=True, nullable=False)
    full_name = db.Column(db.String(50), nullable=False)
    email = db.Column(db.String(50), nullable=False)
    phone = db.Column(db.String(12))
    contacts = db.Column(db.String(100))
    is_email_verified = db.Column(db.Boolean, default=False)
    pwd = db.Column(db.String(256), nullable=False)
    timestamp = db.Column(db.DateTime, default=datetime.utcnow)

    def __repr__(self):
        return self.username

    def check_password(self, password: str):
        """
        Verified users password.

        :param password: user password
        :type password: str
        :return: result of verification
        :rtype: bool
        """
        return check_password_hash(self.pwd, password)

    def create(self):
        if not get_user_by_username(self.username):
            add(self)
            return self
        return

    def set_email(self, new_email: str):
        self.email = new_email
        self.is_email_verified = False
        db.session.commit()

    def set_name(self, new_name: str):
        self.username = new_name
        db.session.commit()

    def set_pwd(self, new_pwd: str):
        self.pwd = generate_password_hash(new_pwd)
        db.session.commit()

    def verify_email(self):
        self.is_email_verified = True
        db.session.commit()

    def get_token(self, token_type: str, expires_in=600):
        return jwt.encode(
            {token_type: self.id, 'exp': time() + expires_in},
            current_app.config['SECRET_KEY'],
            algorithm='HS256'
        )

    @staticmethod
    def verify_token(token: str, token_type: str):
        try:
            user_id = jwt.decode(token, current_app.config['SECRET_KEY'], algorithms=['HS256'])[token_type]
        except Exception as _:
            return
        return get_user_by_id(user_id)


def get_user_by_id(user_id: int) -> User | None:
    """returns user by id if user exists"""
    return User.query.filter_by(id=user_id).first()


def get_user_by_username(username: str) -> User | None:
    """returns user by username if user exists"""
    return User.query.filter_by(username=username).first()


def create_user(user_data: dict) -> User | None:
    """creates User if username is available"""
    user = User(user_data)
    return user.create()


class Role(db.Model):
    """Role model

    :cvar id: autogenerated role id
    :type id: int
    :cvar name: role name
    :type name: str

    """

    def __init__(self, name):
        self.name = name
        self.add()

    __tablename__ = 'role'
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(50), unique=True, nullable=False)

    def add(self):
        try:
            db.session.add(self)
            db.session.commit()
        except Exception as e:
            print(e)
            db.session.rollback()

    def __repr__(self):
        return self.name


class EventMember(db.Model):
    """EventMember model

    :cvar id: autogenerated event member id
    :type id: int
    :cvar nickname: event member`s nickname
    :type nickname: str
    :cvar days_amount: days amount on event
    :type days_amount: int
    :cvar is_drinker: describes if member is drinker
    :type is_drinker: bool
    :cvar money_impact: describes members money impact
    :type money_impact: float
    :cvar role_id: Role foreign key
    :type role_id: int
    :cvar user_id: User foreign key
    :type user_id: int

    :cvar role: role object
    :type role: Role
    :cvar user: user object
    :type user: User

    """

    def __init__(self, member_data: dict):
        self.nickname = member_data.get('nickname')
        self.days_amount = member_data.get('days_amount')
        self.is_drinker = member_data.get('is_drinker')

        add(self)

    __tablename__ = 'event_member'
    id = db.Column(db.Integer(), primary_key=True)
    nickname = db.Column(db.String(50), nullable=False)
    days_amount = db.Column(db.Integer(), nullable=False)
    is_drinker = db.Column(db.Boolean, default=False)
    money_impact = db.Column(db.Float(), default=0)
    role_id = db.Column(db.Integer(), db.ForeignKey('role.id'), nullable=False)
    user_id = db.Column(db.Integer(), db.ForeignKey('user.id'))

    role = db.relationship("Role", foreign_keys=[role_id])
    user = db.relationship("User", foreign_keys=[user_id])

    def add(self):
        try:
            db.session.add(self)
            db.session.commit()
        except Exception as e:
            print(e)
            db.session.rollback()

    def __repr__(self):
        return self.nickname


class Event(db.Model):
    """Event model

    :cvar id: autogenerated event id
    :type id: int
    :cvar title: event title
    :type title: str
    :cvar description: event description
    :type description: str
    :cvar location_id: EventLocation foreign key
    :type location_id: int
    :cvar date_start: event start date
    :type date_start: datetime
    :cvar date_end: event end date
    :type date_end: datetime
    :cvar date_tz: timezone of event in format: [±0000]
    :type date_tz: str
    :cvar cost_reduction_factor: describes percent for cost reduction factor per day
    :type cost_reduction_factor: int
    :cvar creator_id: User foreign key
    :type creator_id: int

    :cvar location: event location object
    :type location: EventLocation
    :cvar members: event members
    :type members: list[EventMember]
    """

    def __init__(self, event_data: dict, creator: User):
        self.title = event_data.get('title')
        self.description = event_data.get('description')
        self.date_start = date_from_str(event_data.get('date_start'))
        self.date_end = date_from_str(event_data.get('date_end'))
        self.date_tz = event_data.get('timezone')
        self.cost_reduction_factor = event_data.get('cost_reduction_factor')

        self.creator = creator
        # todo not secure. check location_id is allowed
        self.location = EventLocation(get_location_by_id(event_data.get('location_id')))

        add(self)

    __tablename__ = 'event'
    id = db.Column(db.Integer(), primary_key=True)
    title = db.Column(db.String(50), nullable=False)
    description = db.Column(db.UnicodeText)
    location_id = db.Column(db.Integer(), db.ForeignKey('event_location.id'), nullable=False)
    date_start = db.Column(db.DateTime, nullable=False)
    date_end = db.Column(db.DateTime, nullable=False)
    date_tz = db.Column(db.String(5), nullable=False)
    cost_reduction_factor = db.Column(db.Integer, default=25, nullable=False)
    creator_id = db.Column(db.Integer(), db.ForeignKey('user.id'), nullable=False)

    creator = db.relationship("User", foreign_keys=[creator_id])
    location = db.relationship("EventLocation", foreign_keys=[location_id])
    members = db.relationship("EventMember", secondary=member_to_event, backref=db.backref('events', lazy=True))

    def __repr__(self):
        return self.title


class Location(db.Model):
    """Location model

    :cvar id: autogenerated location id
    :type id: int
    :cvar name: location name
    :type name: str
    :cvar address: location address
    :type address: str
    :cvar geo: location geo
    :type geo: str
    :cvar maps_link: location maps link
    :type maps_link: str
    :cvar description: location description
    :type description: str
    :cvar creator_id: User foreign key
    :type creator_id: int

    :cvar creator: location creator
    :type creator: User

    """

    def __init__(self, location_data: dict, creator: User):
        self.name = location_data.get('name')
        self.address = location_data.get('address')
        self.geo = location_data.get('geo')
        self.maps_link = location_data.get('maps_link')
        self.description = location_data.get('description')
        self.creator = creator

        add(self)

    __tablename__ = 'location'
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    address = db.Column(db.String(500), nullable=False)
    geo = db.Column(db.String(100), nullable=False)
    maps_link = db.Column(db.String(100), nullable=False)
    description = db.Column(db.UnicodeText)
    creator_id = db.Column(db.Integer(), db.ForeignKey('user.id'), nullable=False)

    creator = db.relationship("User", foreign_keys=[creator_id], backref=db.backref('locations', lazy=True))

    def __repr__(self):
        return self.address

    def to_dict(self):
        return dict(
            id=self.id,
            name=self.name,
            address=self.address,
            geo=self.geo,
            maps_link=self.maps_link,
            description=self.description,
        )

    def update(self, location_data: dict):
        self.name = location_data.get('name')
        self.address = location_data.get('address')
        self.geo = location_data.get('geo')
        self.maps_link = location_data.get('maps_link')
        self.description = location_data.get('description')

        db.session.commit()

    def delete(self):
        delete_obj(self)


def get_location_by_id(location_id: int) -> Location | None:
    """returns location by id if exists"""
    return Location.query.filter_by(id=location_id).first()


class EventLocation(db.Model):
    """Event Location model

    :cvar id: autogenerated location id
    :type id: int
    :cvar name: location name
    :type name: str
    :cvar address: location address
    :type address: str
    :cvar geo: location geo
    :type geo: str
    :cvar maps_link: location maps link
    :type maps_link: str
    :cvar description: location description
    :type description: str

    """

    def __init__(self, location: Location):
        self.name = location.name
        self.address = location.address
        self.geo = location.geo
        self.maps_link = location.maps_link
        self.description = location.description

        add(self)

    __tablename__ = 'event_location'
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    address = db.Column(db.String(500), nullable=False)
    geo = db.Column(db.String(100), nullable=False)
    maps_link = db.Column(db.String(100), nullable=False)
    description = db.Column(db.UnicodeText)

    def __repr__(self):
        return self.address


class ProductCategory(db.Model):
    """ProductCategory model

    :cvar id: autogenerated ProductCategory id
    :type id: int
    :cvar name: ProductCategory name
    :type name: str

    """
    __tablename__ = 'product_category'
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(50), nullable=False, unique=True)

    def __repr__(self):
        return self.name


class ProductType(db.Model):
    """ProductType model

    :cvar id: autogenerated ProductType id
    :type id: int
    :cvar name: ProductType name
    :type name: str

    """
    __tablename__ = 'product_type'
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(50), nullable=False, unique=True)

    def __repr__(self):
        return self.name


class ProductUnit(db.Model):
    """ProductUnit model

    :cvar id: autogenerated ProductUnit id
    :type id: int
    :cvar name: ProductUnit name
    :type name: str

    """
    __tablename__ = 'product_unit'
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(50), nullable=False, unique=True)

    def __repr__(self):
        return self.name


class ProductState(db.Model):
    """ProductState model

    :cvar id: autogenerated ProductState id
    :type id: int
    :cvar name: ProductState name
    :type name: str

    """
    __tablename__ = 'product_state'
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(50), nullable=False, unique=True)

    def __repr__(self):
        return self.name


class BaseProduct(db.Model):
    """BaseProduct model

    :cvar id: autogenerated BaseProduct id
    :type id: int
    :cvar name: BaseProduct name
    :type name: str
    :cvar category_id: ProductCategory foreign key
    :type category_id: int
    :cvar type_id: ProductType foreign key
    :type type_id: int
    :cvar unit_id: ProductUnit foreign key
    :type unit_id: int
    :cvar price_supposed: supposed product price
    :type price_supposed: float

    """
    __tablename__ = 'base_product'
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(50), nullable=False, unique=True)
    category_id = db.Column(db.Integer(), db.ForeignKey('product_category.id'), nullable=False)
    type_id = db.Column(db.Integer(), db.ForeignKey('product_type.id'), nullable=False)
    unit_id = db.Column(db.Integer(), db.ForeignKey('product_unit.id'), nullable=False)
    price_supposed = db.Column(db.Float())

    def __repr__(self):
        return self.name


class Product(db.Model):
    """Product model

    :cvar id: autogenerated BaseProduct id
    :type id: int
    :cvar product_id: BaseProduct foreign key
    :type product_id: int
    :cvar state_id: ProductState foreign key
    :type state_id: int
    :cvar amount: amount of products
    :type amount: int
    :cvar price_final: product purchase price
    :type price_final: float
    :cvar description: product description
    :type description: str
    :cvar market: place of purchase
    :type market: str

    """
    __tablename__ = 'product'
    id = db.Column(db.Integer(), primary_key=True)
    product_id = db.Column(db.Integer(), db.ForeignKey('base_product.id'), nullable=False)
    state_id = db.Column(db.Integer(), db.ForeignKey('product_state.id'), nullable=False)
    amount = db.Column(db.Integer(), nullable=False)
    price_final = db.Column(db.Float())
    description = db.Column(db.UnicodeText)
    market = db.Column(db.String(50))

    def __repr__(self):
        return self.id
